# Generated by Django 5.2.10 on 2026-02-17 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='loanitem',
            new_name='loans_loani_communi_3ba64b_idx',
            old_name='loans_loani_communi_4a10f6_idx',
        ),
        migrations.RenameIndex(
            model_name='loanitem',
            new_name='loans_loani_owner_u_e2e75a_idx',
            old_name='loans_loani_owner_u_959f75_idx',
        ),
        migrations.RenameIndex(
            model_name='loanrequest',
            new_name='loans_loanr_item_id_4aa781_idx',
            old_name='loans_loanr_item_id_4f8773_idx',
        ),
        migrations.RenameIndex(
            model_name='loanrequest',
            new_name='loans_loanr_request_cd348f_idx',
            old_name='loans_loanr_request_f66f85_idx',
        ),
    ]
